package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;

public class DAACoachData extends AttributeContainer implements KvmSerializable
{

    
    public String coachClass;
    
    public DAAToiletAvailabilityType toilet;
    
    public Integer loading;
    
    public String number;
    private transient Object __source;
    

    
    
    
    public void loadFromSoap(Object paramObj,DAAExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("number"))
        {	
            Object j = inObj.getAttribute("number");
            if (j != null)
            {
                number = j.toString();
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,DAAExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("coachClass"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.coachClass = j.toString();
                    }
                }
                else if (obj instanceof String){
                    this.coachClass = (String)obj;
                }
            }
            return true;
        }
        if (info.name.equals("toilet"))
        {
            if(obj!=null)
            {
                Object j = obj;
                this.toilet = (DAAToiletAvailabilityType)__envelope.get(j,DAAToiletAvailabilityType.class,false);
            }
            return true;
        }
        if (info.name.equals("loading"))
        {
            if(obj!=null)
            {
                if (obj.getClass().equals(SoapPrimitive.class))
                {
                    SoapPrimitive j =(SoapPrimitive) obj;
                    if(j.toString()!=null)
                    {
                        this.loading = Integer.parseInt(j.toString());
                    }
                }
                else if (obj instanceof Integer){
                    this.loading = (Integer)obj;
                }
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex==0)
        {
            return this.coachClass!=null?this.coachClass:SoapPrimitive.NullSkip;
        }
        if(propertyIndex==1)
        {
            return this.toilet!=null?this.toilet.getSimpleValue():null;
        }
        if(propertyIndex==2)
        {
            return this.loading!=null?this.loading:SoapPrimitive.NullSkip;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 3;
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex==0)
        {
            info.type = PropertyInfo.STRING_CLASS;
            info.name = "coachClass";
            info.namespace= "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
        if(propertyIndex==1)
        {
            info.type = org.ksoap2.serialization.SoapPrimitive.class;
            info.name = "toilet";
            info.namespace= "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
        if(propertyIndex==2)
        {
            info.type = PropertyInfo.INTEGER_CLASS;
            info.name = "loading";
            info.namespace= "http://thalesgroup.com/RTTI/2017-10-01/ldb/types";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 1;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "number";
            info.namespace= "";
            if(this.number!=null)
            {
                info.setValue(this.number);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

