package com.example.testSoap.wcf;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------



public interface DAAIServiceEvents
{
    public void Starting();
    public void Completed(DAAOperationResult result);
}
