package com.example.travelinfo.ldbws;

//----------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 5.5.0.6
//
// Created by Quasar Development 
//
//---------------------------------------------------


import java.util.Hashtable;
import org.ksoap2.serialization.*;
import java.util.ArrayList;
import org.ksoap2.serialization.PropertyInfo;

public class DAAArrayOfCallingPoints extends AttributeContainer implements KvmSerializable
{

    
    public ArrayList< DAACallingPoint> callingPoint =new ArrayList<DAACallingPoint >();
    
    public DAAEnums.ServiceType serviceType;
    
    public Boolean serviceChangeRequired;
    
    public Boolean assocIsCancelled;
    private transient Object __source;
    

    
    
    
    public void loadFromSoap(Object paramObj,DAAExtendedSoapSerializationEnvelope __envelope)
    {
        if (paramObj == null)
            return;
        AttributeContainer inObj=(AttributeContainer)paramObj;
        __source=inObj; 
        if(inObj instanceof SoapObject)
        {
            SoapObject soapObject=(SoapObject)inObj;
            int size = soapObject.getPropertyCount();
            for (int i0=0;i0< size;i0++)
            {
                PropertyInfo info=soapObject.getPropertyInfo(i0);
                if(!loadProperty(info,soapObject,__envelope))
                {
                }
            } 
        }
        if (inObj.hasAttribute("serviceType"))
        {	
            Object j = inObj.getAttribute("serviceType");
            if (j != null)
            {
                serviceType = DAAEnums.ServiceType.fromString(j.toString());
            }
        }
        if (inObj.hasAttribute("serviceChangeRequired"))
        {	
            Object j = inObj.getAttribute("serviceChangeRequired");
            if (j != null)
            {
                serviceChangeRequired = new Boolean(j.toString());
            }
        }
        if (inObj.hasAttribute("assocIsCancelled"))
        {	
            Object j = inObj.getAttribute("assocIsCancelled");
            if (j != null)
            {
                assocIsCancelled = new Boolean(j.toString());
            }
        }

    }

    
    protected boolean loadProperty(PropertyInfo info,SoapObject soapObject,DAAExtendedSoapSerializationEnvelope __envelope)
    {
        Object obj = info.getValue();
        if (info.name.equals("callingPoint"))
        {
            if(obj!=null)
            {
                if(this.callingPoint==null)
                {
                    this.callingPoint = new ArrayList< DAACallingPoint>();
                }
                Object j =obj;
                DAACallingPoint j1= (DAACallingPoint)__envelope.get(j,DAACallingPoint.class,false);
                this.callingPoint.add(j1);
            }
            return true;
        }
        return false;
    }
    
    public Object getOriginalXmlSource()
    {
        return __source;
    }    
    

    @Override
    public Object getProperty(int propertyIndex) {
        //!!!!! If you have a compilation error here then you are using old version of ksoap2 library. Please upgrade to the latest version.
        //!!!!! You can find a correct version in Lib folder from generated zip file!!!!!
        if(propertyIndex>=0 && propertyIndex < 0+this.callingPoint.size())
        {
            Object callingPoint = this.callingPoint.get(propertyIndex-(0));
            return callingPoint!=null?callingPoint:SoapPrimitive.NullNilElement;
        }
        return null;
    }


    @Override
    public int getPropertyCount() {
        return 0+callingPoint.size();
    }

    @Override
    public void getPropertyInfo(int propertyIndex, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
    {
        if(propertyIndex>=0 && propertyIndex < 0+this.callingPoint.size())
        {
            info.type = DAACallingPoint.class;
            info.name = "callingPoint";
            info.namespace= "http://thalesgroup.com/RTTI/2015-11-27/ldb/types";
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1)
    {
    }



    @Override
    public int getAttributeCount() {
        return 3;
    }
    
    @Override
    public void getAttributeInfo(int index, AttributeInfo info) {
        if(index==0)
        {
            info.name = "serviceType";
            info.namespace= "";
            if(this.serviceType!=null)
            {
                info.setValue(this.serviceType);
            }
            
        }
        if(index==1)
        {
            info.name = "serviceChangeRequired";
            info.namespace= "";
            if(this.serviceChangeRequired!=null)
            {
                info.setValue(this.serviceChangeRequired);
            }
            
        }
        if(index==2)
        {
            info.name = "assocIsCancelled";
            info.namespace= "";
            if(this.assocIsCancelled!=null)
            {
                info.setValue(this.assocIsCancelled);
            }
            
        }
    }

    @Override
    public void getAttribute(int i, AttributeInfo attributeInfo) {

    }

    @Override
    public void setAttribute(AttributeInfo attributeInfo) {

    }    
}

